# Generated by Django 3.1.3 on 2020-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinTrack',
            fields=[
                ('id_bin_track', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bin_track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarGps',
            fields=[
                ('id_car_gps', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.TextField(blank=True, null=True)),
                ('date_create', models.DateTimeField()),
            ],
            options={
                'db_table': 'car_gps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_cars', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(blank=True, max_length=45, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('date_oil', models.DateField(blank=True, null=True)),
                ('mileage_oil', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id_car_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'car_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GarbageDump',
            fields=[
                ('id_garbage_dump', models.AutoField(primary_key=True, serialize=False)),
                ('address_gps', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'garbage_dump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id_invoices', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date_of_invoice', models.DateTimeField(blank=True, null=True)),
                ('date_of_service', models.DateTimeField(blank=True, null=True)),
                ('name_of_service', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_items', models.IntegerField(blank=True, null=True)),
                ('price_netto', models.IntegerField(blank=True, null=True)),
                ('full_price_netto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicesNames',
            fields=[
                ('id_invoices_names', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('nip', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoices_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id_report_problem', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_report', models.CharField(blank=True, max_length=45, null=True)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'report_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id_track', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.IntegerField(blank=True, null=True)),
                ('driver', models.IntegerField(blank=True, null=True)),
                ('manager', models.IntegerField(blank=True, null=True)),
                ('date_of_loan_keys', models.DateTimeField(blank=True, null=True)),
                ('date_return_keys', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id_trash_bin', models.AutoField(primary_key=True, serialize=False)),
                ('bin_capacity', models.CharField(blank=True, max_length=45, null=True)),
                ('bin_type', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('bin_size', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'trash_bin',
                'managed': False,
            },
        ),
    ]
