# Generated by Django 3.1.3 on 2021-01-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bintrack',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='garbagedump',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoicesnames',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='keys',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trashbin',
            options={'managed': False},
        ),
    ]
