# Generated by Django 3.1.3 on 2021-01-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20210104_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bintrack',
            options={'managed': False, 'ordering': ['id_bin_track']},
        ),
        migrations.AlterModelOptions(
            name='keys',
            options={'managed': False, 'ordering': ['id_keys']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': False, 'ordering': ['id_track']},
        ),
    ]
